window.BMF_DETAILED_PRODUCTS = [
  {
    "id": "sea-s01-01",
    "name": "กุ้งขาว ทุกไซซ์",
    "category": "ทะเลสด",
    "featured": true,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-01.webp"
  },
  {
    "id": "sea-s01-02",
    "name": "กุ้งแม่น้ำ ตัวผู้",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-02.webp"
  },
  {
    "id": "sea-s01-03",
    "name": "กุ้งแม่น้ำ ตัวเมีย",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-03.webp"
  },
  {
    "id": "sea-s01-04",
    "name": "กุ้งโก๋",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-04.webp"
  },
  {
    "id": "sea-s01-05",
    "name": "กุ้งเมียนิ่ม",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-05.webp"
  },
  {
    "id": "sea-s01-06",
    "name": "ปูม้าสด",
    "category": "ทะเลสด",
    "featured": true,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-06.webp"
  },
  {
    "id": "sea-s01-07",
    "name": "ปูลาย",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-07.webp"
  },
  {
    "id": "sea-s01-08",
    "name": "หอยแครง",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-08.webp"
  },
  {
    "id": "sea-s01-09",
    "name": "หมึกต่างๆ",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-s01-09.webp"
  },
  {
    "id": "sea-f08-01",
    "name": "กระดองเจาะ",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-01.webp"
  },
  {
    "id": "sea-f08-02",
    "name": "หมึกศอก",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-02.webp"
  },
  {
    "id": "sea-f08-03",
    "name": "กุ้งแม่น้ำ ตัวเมีย",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-03.webp"
  },
  {
    "id": "sea-f08-04",
    "name": "หมึกไข่",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-04.webp"
  },
  {
    "id": "sea-f08-05",
    "name": "หมึกสาย",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-05.webp"
  },
  {
    "id": "sea-f08-06",
    "name": "หมึกหอม",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-06.webp"
  },
  {
    "id": "sea-f08-07",
    "name": "หมึกลวก",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-07.webp"
  },
  {
    "id": "sea-f08-08",
    "name": "หมึกดำ",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-08.webp"
  },
  {
    "id": "sea-f08-09",
    "name": "หมึกผ่า",
    "category": "ทะเลสด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก. · รอแอดมินระบุไซซ์และราคา",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/sea-f08-09.webp"
  },
  {
    "id": "pork-p01-01",
    "name": "หมูหมักทุกรสชาติ AA",
    "category": "หมู",
    "featured": true,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 130,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p01-01.webp"
  },
  {
    "id": "pork-p01-02",
    "name": "หมูหมักทุกรสชาติ A",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 115,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p01-02.webp"
  },
  {
    "id": "pork-p01-03",
    "name": "หมูหมักทุกรสชาติ B",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 95,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p01-03.webp"
  },
  {
    "id": "pork-p01-04",
    "name": "หมูหมักทุกรสชาติ C",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 85,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p01-04.webp"
  },
  {
    "id": "pork-p02-01",
    "name": "สามชั้นหมักทุกรสชาติ AA",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 150,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p02-01.webp"
  },
  {
    "id": "pork-p02-02",
    "name": "สามชั้นหมักทุกรสชาติ A",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 135,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p02-02.webp"
  },
  {
    "id": "pork-p02-03",
    "name": "สามชั้นหมักทุกรสชาติ B",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 115,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p02-03.webp"
  },
  {
    "id": "pork-p02-04",
    "name": "สามชั้นหมักทุกรสชาติ C",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 5 กก. · ขั้นต่ำ 10 กก.",
    "price": 95,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p02-04.webp"
  },
  {
    "id": "pork-p03-01",
    "name": "สันคอ A",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 185,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-01.webp"
  },
  {
    "id": "pork-p03-02",
    "name": "สันคอ B",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 175,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-02.webp"
  },
  {
    "id": "pork-p03-03",
    "name": "สามชั้นลอกหนัง B",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 125,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-03.webp"
  },
  {
    "id": "pork-p03-04",
    "name": "สามชั้นติดหนังแรปกลม A",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 190,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-04.webp"
  },
  {
    "id": "pork-p03-05",
    "name": "สามชั้นลอกหนัง AA",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 205,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-05.webp"
  },
  {
    "id": "pork-p03-06",
    "name": "สามชั้นติดหนังแรปแท่ง B",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 175,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-06.webp"
  },
  {
    "id": "pork-p03-07",
    "name": "สันนอก",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 145,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-07.webp"
  },
  {
    "id": "pork-p03-08",
    "name": "สะโพก",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 145,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-08.webp"
  },
  {
    "id": "pork-p03-09",
    "name": "สันคอชาบู",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 125,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p03-09.webp"
  },
  {
    "id": "pork-p04-01",
    "name": "สะโพกสไลด์",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 135,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p04-01.webp"
  },
  {
    "id": "pork-p04-02",
    "name": "สันคอชาบู",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 130,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p04-02.webp"
  },
  {
    "id": "pork-p04-03",
    "name": "หมูชาบู",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 115,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p04-03.webp"
  },
  {
    "id": "pork-p04-04",
    "name": "หมูกลมสไลด์",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 105,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p04-04.webp"
  },
  {
    "id": "pork-p05-01",
    "name": "หมูชาบู",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 105,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p05-01.webp"
  },
  {
    "id": "pork-p05-02",
    "name": "หมูกลม",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 100,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p05-02.webp"
  },
  {
    "id": "pork-p05-03",
    "name": "สองชั้น",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 125,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p05-03.webp"
  },
  {
    "id": "pork-p06-01",
    "name": "สองชั้นแท้",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 140,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p06-01.webp"
  },
  {
    "id": "pork-p06-02",
    "name": "สองชั้นเทียม",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 120,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p06-02.webp"
  },
  {
    "id": "pork-p06-03",
    "name": "สามชั้นลอกหนังสไลด์",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 125,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p06-03.webp"
  },
  {
    "id": "pork-p06-04",
    "name": "ไก่กลมดำ",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 100,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p06-04.webp"
  },
  {
    "id": "pork-p07-01",
    "name": "สันคอสไลด์ชาบู 2 มิล",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 170,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p07-01.webp"
  },
  {
    "id": "pork-p07-02",
    "name": "สันคอสไลด์หมูกระทะ 3 มิล",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 170,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p07-02.webp"
  },
  {
    "id": "pork-p07-03",
    "name": "สามชั้นสไลด์ 3.5 มิล AA",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 195,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p07-03.webp"
  },
  {
    "id": "pork-p07-04",
    "name": "สามชั้นสไลด์ A",
    "category": "หมู",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 170,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p07-04.webp"
  },
  {
    "id": "pork-p08-01",
    "name": "ตับสไลด์ AA",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 1 กก. · ขั้นต่ำ 5 กก.",
    "price": 95,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p08-01.webp"
  },
  {
    "id": "pork-p08-02",
    "name": "ตับสไลด์ A",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 1 กก. · ขั้นต่ำ 5 กก.",
    "price": 85,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p08-02.webp"
  },
  {
    "id": "pork-p08-03",
    "name": "ตับสไลด์ B",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 1 กก. · ขั้นต่ำ 5 กก.",
    "price": 75,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p08-03.webp"
  },
  {
    "id": "pork-p08-04",
    "name": "จิ๊สไลด์",
    "category": "หมู",
    "featured": false,
    "size": "แพ็ก 1 กก. · ขั้นต่ำ 5 กก.",
    "price": 75,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/pork-p08-04.webp"
  },
  {
    "id": "fr-f01-01",
    "name": "ดอลลี่ไม่ติดท้อง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": true,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 45,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-01.webp"
  },
  {
    "id": "fr-f01-02",
    "name": "หมึกบั้ง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 52,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-02.webp"
  },
  {
    "id": "fr-f01-03",
    "name": "หมึกวง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 59,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-03.webp"
  },
  {
    "id": "fr-f01-04",
    "name": "แมลงภู่ชิลี",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 57,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-04.webp"
  },
  {
    "id": "fr-f01-05",
    "name": "หนวดหมึก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 57,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-05.webp"
  },
  {
    "id": "fr-f01-06",
    "name": "หมึกหั่น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 56,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-06.webp"
  },
  {
    "id": "fr-f01-07",
    "name": "หนวดเรด้าติดโคน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 69,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-07.webp"
  },
  {
    "id": "fr-f01-08",
    "name": "คอเอ็นแก้ว",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 39,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-08.webp"
  },
  {
    "id": "fr-f01-09",
    "name": "เนื้อหอยแมลงภู่ชิลี",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 79,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f01-09.webp"
  },
  {
    "id": "fr-f02-01",
    "name": "แมงกะพรุนจืดขาล้วน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 80,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-01.webp"
  },
  {
    "id": "fr-f02-02",
    "name": "แมงกะพรุนจืดผ่าครึ่ง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 55,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-02.webp"
  },
  {
    "id": "fr-f02-03",
    "name": "แมงกะพรุนจืดผ่า 7/3",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 แพ็ก",
    "price": 35,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fr-f02-03.webp"
  },
  {
    "id": "fr-f02-04",
    "name": "สไบนางหั่น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 160,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-04.webp"
  },
  {
    "id": "fr-f02-05",
    "name": "หมึกกรอบหั่น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": true,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 99,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-05.webp"
  },
  {
    "id": "fr-f02-06",
    "name": "หมึกกรอบตัว",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 99,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-06.webp"
  },
  {
    "id": "fr-f02-07",
    "name": "ขายำ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 68,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-07.webp"
  },
  {
    "id": "fr-f02-08",
    "name": "ไส้ตันต้ม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 118,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-08.webp"
  },
  {
    "id": "fr-f02-09",
    "name": "สไบนางผืน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 160,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f02-09.webp"
  },
  {
    "id": "fr-f03-01",
    "name": "ดอลลี่ตัว NW 80%",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 83,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f03-01.webp"
  },
  {
    "id": "fr-f03-02",
    "name": "ดอลลี่หั่น 70% ไม่ติดท้อง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 73,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f03-02.webp"
  },
  {
    "id": "fr-f03-03",
    "name": "ดอลลี่ติดท้อง 70%",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 76,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f03-03.webp"
  },
  {
    "id": "fr-f03-04",
    "name": "หมึกอมริกา 10/15 ตัวโล",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 15 โล",
    "price": 110,
    "unit": "แพ็ก 200 กรัม",
    "status": "in",
    "image": "images/items/fr-f03-04.webp"
  },
  {
    "id": "fr-f04-01",
    "name": "OK เบคอน 500 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 70,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fr-f04-01.webp"
  },
  {
    "id": "fr-f04-02",
    "name": "ปูจดฟรีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ราคาตามไซซ์ · ขั้นต่ำ 10 กก.",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f04-02.webp"
  },
  {
    "id": "fr-f04-03",
    "name": "หอยเชลล์ 15 ฝา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 14 ถาด",
    "price": 49,
    "unit": "ถาด",
    "status": "in",
    "image": "images/items/fr-f04-03.webp"
  },
  {
    "id": "fr-f04-04",
    "name": "ชีสยืด ฟิน 200 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 แพ็ก",
    "price": 65,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fr-f04-04.webp"
  },
  {
    "id": "fr-f05-01",
    "name": "เต้าหู้ปลา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 50,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f05-01.webp"
  },
  {
    "id": "fr-f05-02",
    "name": "กุ้งพันสาหร่าย 500 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 แพ็ก",
    "price": 55,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fr-f05-02.webp"
  },
  {
    "id": "fr-f05-03",
    "name": "ท้องม่อนป้ายแดง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 โล",
    "price": 145,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f05-03.webp"
  },
  {
    "id": "fr-f05-04",
    "name": "ท้องม่อน B",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 โล",
    "price": 80,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f05-04.webp"
  },
  {
    "id": "fr-f06-01",
    "name": "ไข่หมึก AAA",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 250,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f06-01.webp"
  },
  {
    "id": "fr-f06-02",
    "name": "สาหร่ายวากาเมะแห้ง 100 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 5 แพ็ก",
    "price": 95,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fr-f06-02.webp"
  },
  {
    "id": "fr-f06-03",
    "name": "ยำสาหร่าย",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 โล",
    "price": 90,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f06-03.webp"
  },
  {
    "id": "fr-f06-04",
    "name": "หอยหวานฟรีส 30/50",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 12 โล",
    "price": 150,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f06-04.webp"
  },
  {
    "id": "fr-f07-01",
    "name": "บุกไข่",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 75,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f07-01.webp"
  },
  {
    "id": "fr-f07-02",
    "name": "บุกขาว",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 65,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f07-02.webp"
  },
  {
    "id": "fr-f07-03",
    "name": "มันก้อน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 63,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f07-03.webp"
  },
  {
    "id": "fr-f07-04",
    "name": "หมูเด้งตุ้ม 450 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 ถุง",
    "price": 45,
    "unit": "ถุง",
    "status": "in",
    "image": "images/items/fr-f07-04.webp"
  },
  {
    "id": "fr-f09-01",
    "name": "ปลาไข่ 28–30 ตัว/โล",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 100,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f09-01.webp"
  },
  {
    "id": "fr-f09-02",
    "name": "ข้าวโพดหวาน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 10 กก.",
    "price": 65,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f09-02.webp"
  },
  {
    "id": "fr-f09-03",
    "name": "แฮมเหลี่ยม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 5 โล",
    "price": 90,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f09-03.webp"
  },
  {
    "id": "fr-f09-04",
    "name": "แฮมกลม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 5 โล",
    "price": 75,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fr-f09-04.webp"
  },
  {
    "id": "fried-d01-01",
    "name": "เฟรนฟราย 7 มิล",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "10 มิล 52 บาท/กก.",
    "price": 49,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/fried-d01-01.webp"
  },
  {
    "id": "fried-d01-02",
    "name": "นักเก็ตไก่ดั้งเดิม ซันวาเลย์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 120,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-02.webp"
  },
  {
    "id": "fried-d01-03",
    "name": "ไก่ป๊อปดั้งเดิม ซันวาเลย์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 118,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-03.webp"
  },
  {
    "id": "fried-d01-04",
    "name": "ไก่คาราเกะ ปันสุข",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 118,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-04.webp"
  },
  {
    "id": "fried-d01-05",
    "name": "ไก่ป๊อปดั้งเดิม ปันสุข",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 115,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-05.webp"
  },
  {
    "id": "fried-d01-06",
    "name": "นักเก็ตไก่ ปันสุข",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 118,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-06.webp"
  },
  {
    "id": "fried-d01-07",
    "name": "ไก่ป๊อป Top Food",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 92,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-07.webp"
  },
  {
    "id": "fried-d01-08",
    "name": "นักเก็ตไก่ Top Food",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 95,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-08.webp"
  },
  {
    "id": "fried-d01-09",
    "name": "ไก่ดาว Top Food",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 85,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d01-09.webp"
  },
  {
    "id": "fried-d02-01",
    "name": "ขนมจีบหมู/กุ้ง แพนด้า",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "420 กรัม 30 ลูก · ลัง 10 แพ็ก",
    "price": 85,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-01.webp"
  },
  {
    "id": "fried-d02-02",
    "name": "เกี๊ยวซ่าไก่ แพนด้า",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "360 กรัม 20 ชิ้น · ลัง 10 แพ็ก",
    "price": 62,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-02.webp"
  },
  {
    "id": "fried-d02-03",
    "name": "ฮอกชีส 15 ไม้",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 73,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-03.webp"
  },
  {
    "id": "fried-d02-04",
    "name": "ชีสบอล 24 ลูก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 79,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-04.webp"
  },
  {
    "id": "fried-d02-05",
    "name": "มินิชีสบอล 48 ลูก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 82,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-05.webp"
  },
  {
    "id": "fried-d02-06",
    "name": "ชีสสติ๊ก 13 ชิ้น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 85,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-06.webp"
  },
  {
    "id": "fried-d02-07",
    "name": "กุ้งตอปิโด คำโต 10 ชิ้น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 10 แพ็ก",
    "price": 65,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-07.webp"
  },
  {
    "id": "fried-d02-08",
    "name": "ไก่จ๊อห้าดาว ต้นตำรับ 500 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ลัง 20 แพ็ก",
    "price": 85,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-08.webp"
  },
  {
    "id": "fried-d02-09",
    "name": "เกี๊ยวซูชิ 22 ชิ้น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ห่อละ 10 แพ็ก",
    "price": 85,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/fried-d02-09.webp"
  },
  {
    "id": "beef-01",
    "name": "ริบอาย",
    "category": "เนื้อ",
    "featured": true,
    "size": "ราคาต่อกก.",
    "price": 230,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-01.webp"
  },
  {
    "id": "beef-01-250g",
    "name": "ริบอาย สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 105,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-01.webp"
  },
  {
    "id": "beef-01-500g",
    "name": "ริบอาย สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 150,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-01.webp"
  },
  {
    "id": "beef-02",
    "name": "ใบพายลายใบไม้",
    "category": "เนื้อ",
    "featured": true,
    "size": "ราคาต่อกก.",
    "price": 240,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-02.webp"
  },
  {
    "id": "beef-02-250g",
    "name": "ใบพายลายใบไม้ สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 105,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-02.webp"
  },
  {
    "id": "beef-02-500g",
    "name": "ใบพายลายใบไม้ สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 150,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-02.webp"
  },
  {
    "id": "beef-03",
    "name": "สันคอ",
    "category": "เนื้อ",
    "featured": false,
    "size": "ราคาต่อกก.",
    "price": 200,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-03.webp"
  },
  {
    "id": "beef-03-250g",
    "name": "สันคอ สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 105,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-03.webp"
  },
  {
    "id": "beef-03-500g",
    "name": "สันคอ สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 145,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-03.webp"
  },
  {
    "id": "beef-04",
    "name": "สามชั้น",
    "category": "เนื้อ",
    "featured": false,
    "size": "ราคาต่อกก.",
    "price": 195,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-04.webp"
  },
  {
    "id": "beef-04-250g",
    "name": "สามชั้น สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 100,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-04.webp"
  },
  {
    "id": "beef-04-500g",
    "name": "สามชั้น สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 140,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-04.webp"
  },
  {
    "id": "beef-05",
    "name": "เสือออสเตรเลีย ไขมันขาว",
    "category": "เนื้อ",
    "featured": false,
    "size": "285–305 บาท/กก.",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-05.webp"
  },
  {
    "id": "beef-05-250g",
    "name": "เสือออสเตรเลีย ไขมันขาว สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 115,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-05.webp"
  },
  {
    "id": "beef-05-500g",
    "name": "เสือออสเตรเลีย ไขมันขาว สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 170,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-05.webp"
  },
  {
    "id": "beef-06",
    "name": "เสือออสเตรเลีย ไขมันเหลือง",
    "category": "เนื้อ",
    "featured": false,
    "size": "255–275 บาท/กก.",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-06.webp"
  },
  {
    "id": "beef-06-250g",
    "name": "เสือออสเตรเลีย ไขมันเหลือง สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 115,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-06.webp"
  },
  {
    "id": "beef-06-500g",
    "name": "เสือออสเตรเลีย ไขมันเหลือง สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 170,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-06.webp"
  },
  {
    "id": "beef-07",
    "name": "โหนก",
    "category": "เนื้อ",
    "featured": false,
    "size": "ราคาต่อกก.",
    "price": 285,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-07.webp"
  },
  {
    "id": "beef-07-250g",
    "name": "โหนก สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 115,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-07.webp"
  },
  {
    "id": "beef-07-500g",
    "name": "โหนก สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 170,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-07.webp"
  },
  {
    "id": "beef-08",
    "name": "น่องลาย",
    "category": "เนื้อ",
    "featured": false,
    "size": "ราคาต่อกก.",
    "price": 225,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-08.webp"
  },
  {
    "id": "beef-08-250g",
    "name": "น่องลาย สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 105,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-08.webp"
  },
  {
    "id": "beef-08-500g",
    "name": "น่องลาย สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 150,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-08.webp"
  },
  {
    "id": "beef-09",
    "name": "เสือร้องไห้",
    "category": "เนื้อ",
    "featured": false,
    "size": "ราคาต่อกก.",
    "price": 215,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-09.webp"
  },
  {
    "id": "beef-09-250g",
    "name": "เสือร้องไห้ สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 105,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-09.webp"
  },
  {
    "id": "beef-09-500g",
    "name": "เสือร้องไห้ สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 150,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-09.webp"
  },
  {
    "id": "beef-10",
    "name": "ลิ้นวัวลอก",
    "category": "เนื้อ",
    "featured": false,
    "size": "255–300 บาท/กก.",
    "price": null,
    "unit": "กก.",
    "status": "in",
    "image": "images/items/beef-10.webp"
  },
  {
    "id": "beef-10-250g",
    "name": "ลิ้นวัวลอก สไลด์ 250 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 250 กรัม",
    "price": 105,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-10.webp"
  },
  {
    "id": "beef-10-500g",
    "name": "ลิ้นวัวลอก สไลด์ 500 กรัม",
    "category": "เนื้อ",
    "featured": false,
    "size": "แพ็ก 500 กรัม",
    "price": 150,
    "unit": "แพ็ก",
    "status": "in",
    "image": "images/items/beef-10.webp"
  },
  {
    "id": "mb-m01-01",
    "name": "ซาลาเปาปลาไส้ครีมชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1600,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m01-01.webp"
  },
  {
    "id": "mb-m01-02",
    "name": "คอมโบฟิชบัน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1670,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m01-02.webp"
  },
  {
    "id": "mb-m01-03",
    "name": "ซาลาเปาปลาสอดไส้ซอสหม่าล่า",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1620,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m01-03.webp"
  },
  {
    "id": "mb-m01-04",
    "name": "ซาลาเปาปลาไส้ข้าวโพดครีมชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1550,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m01-04.webp"
  },
  {
    "id": "mb-m01-05",
    "name": "ซาลาเปาปลาไส้ไข่กุ้ง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1700,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m01-05.webp"
  },
  {
    "id": "mb-m01-06",
    "name": "ซาลาเปาปลาไส้ไข่เค็ม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1650,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m01-06.webp"
  },
  {
    "id": "mb-m02-01",
    "name": "ฟองเต้าหู้ปูอัด",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 875,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m02-01.webp"
  },
  {
    "id": "mb-m02-02",
    "name": "เปาเปา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1550,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m02-02.webp"
  },
  {
    "id": "mb-m02-03",
    "name": "เปาทูโทนไส้ไข่กุ้ง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1730,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m02-03.webp"
  },
  {
    "id": "mb-m02-04",
    "name": "โฟมสติ๊ก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 800,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m02-04.webp"
  },
  {
    "id": "mb-m02-05",
    "name": "ฟิชดัมเบลล์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1580,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m02-05.webp"
  },
  {
    "id": "mb-m02-06",
    "name": "ดับเบิ้ลชีสปูอัด",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1025,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m02-06.webp"
  },
  {
    "id": "mb-m03-01",
    "name": "ออมุก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 840,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m03-01.webp"
  },
  {
    "id": "mb-m03-02",
    "name": "เต้าหู้ปลาผสมชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1450,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m03-02.webp"
  },
  {
    "id": "mb-m03-03",
    "name": "ยากิแครบ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 765,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m03-03.webp"
  },
  {
    "id": "mb-m03-04",
    "name": "กุ้งผสมชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 775,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m03-04.webp"
  },
  {
    "id": "mb-m03-05",
    "name": "กุ้งรสต้มวุ้นเส้น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 750,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m03-05.webp"
  },
  {
    "id": "mb-m03-06",
    "name": "ชาบู 8 เซียน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1520,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m03-06.webp"
  },
  {
    "id": "mb-m04-01",
    "name": "รวมมิตรลูกชิ้น 1 กก.",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1450,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m04-01.webp"
  },
  {
    "id": "mb-m04-02",
    "name": "รวมมิตรลูกชิ้น 500 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1700,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m04-02.webp"
  },
  {
    "id": "mb-m04-03",
    "name": "เส้นปลา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1390,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m04-03.webp"
  },
  {
    "id": "mb-m04-04",
    "name": "แองกรี้เบิร์ด มิกซ์เซ็ต",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1570,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m04-04.webp"
  },
  {
    "id": "mb-m04-05",
    "name": "ชิกุวะสไตล์ญี่ปุ่น",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1300,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m04-05.webp"
  },
  {
    "id": "mb-m04-06",
    "name": "ปลาหมึกหลอดยาว",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1250,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m04-06.webp"
  },
  {
    "id": "mb-m05-01",
    "name": "ปลาหลอด A",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1260,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m05-01.webp"
  },
  {
    "id": "mb-m05-02",
    "name": "ปลาหลอด B 250 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1240,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m05-02.webp"
  },
  {
    "id": "mb-m05-03",
    "name": "ปลาหลอด B 500 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1220,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m05-03.webp"
  },
  {
    "id": "mb-m05-04",
    "name": "ลูกชิ้นปลาบุ๋ม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1260,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m05-04.webp"
  },
  {
    "id": "mb-m05-05",
    "name": "ปลาม้วนไส้ชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 2190,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m05-05.webp"
  },
  {
    "id": "mb-m05-06",
    "name": "ปลาทิพย์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1210,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m05-06.webp"
  },
  {
    "id": "mb-m06-01",
    "name": "ปลาแพนดี้ สีชมพู",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m06-01.webp"
  },
  {
    "id": "mb-m06-02",
    "name": "ปลาแพนด้า",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m06-02.webp"
  },
  {
    "id": "mb-m06-03",
    "name": "ปลาการ์ตูน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1350,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m06-03.webp"
  },
  {
    "id": "mb-m06-04",
    "name": "ตัวปลา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1310,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m06-04.webp"
  },
  {
    "id": "mb-m06-05",
    "name": "ฟรุตตี้ฟิชเค้ก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1430,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m06-05.webp"
  },
  {
    "id": "mb-m06-06",
    "name": "ซูซูฟิชเค้ก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1430,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m06-06.webp"
  },
  {
    "id": "mb-m07-01",
    "name": "ปูอัดคานิจัง 7 ซม. 500 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1100,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m07-01.webp"
  },
  {
    "id": "mb-m07-02",
    "name": "ปูอัดคานิจัง 7 ซม. 250 กรัม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1130,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m07-02.webp"
  },
  {
    "id": "mb-m07-03",
    "name": "ปูอัดคานิจัง 12 ซม.",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1100,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m07-03.webp"
  },
  {
    "id": "mb-m07-05",
    "name": "ซูเปอร์อลาสก้า",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1175,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m07-05.webp"
  },
  {
    "id": "mb-m07-06",
    "name": "ปลาเซี่ยงไฮ้",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 885,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m07-06.webp"
  },
  {
    "id": "mb-m08-01",
    "name": "ก้ามปูซูชิ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1440,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m08-01.webp"
  },
  {
    "id": "mb-m08-02",
    "name": "ก้ามปูเทียม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1440,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m08-02.webp"
  },
  {
    "id": "mb-m08-03",
    "name": "ปูทอง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1250,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m08-03.webp"
  },
  {
    "id": "mb-m08-04",
    "name": "ปูซิ่ง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m08-04.webp"
  },
  {
    "id": "mb-m08-05",
    "name": "ปูหลอด",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1390,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m08-05.webp"
  },
  {
    "id": "mb-m08-06",
    "name": "ปูซูชิ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1010,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m08-06.webp"
  },
  {
    "id": "mb-m09-01",
    "name": "ปูอัดเอ็กซ์ตร้า 5 กก.",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 800,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m09-01.webp"
  },
  {
    "id": "mb-m09-02",
    "name": "ปูอัดเอ็กซ์ตร้า 10 กก.",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1400,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m09-02.webp"
  },
  {
    "id": "mb-m09-03",
    "name": "ปูเบนโตะซองแดง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1540,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m09-03.webp"
  },
  {
    "id": "mb-m09-04",
    "name": "ปูเบนโตะสติ๊กเกอร์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1540,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m09-04.webp"
  },
  {
    "id": "mb-m09-05",
    "name": "ปูอัดทูโทนไส้ชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1420,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m09-05.webp"
  },
  {
    "id": "mb-m09-06",
    "name": "ปูอัดนามิ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1230,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m09-06.webp"
  },
  {
    "id": "mb-m10-01",
    "name": "ปูปาร์ตี้",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1090,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m10-01.webp"
  },
  {
    "id": "mb-m10-02",
    "name": "ปูไลน์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m10-02.webp"
  },
  {
    "id": "mb-m10-03",
    "name": "ปูอัดจัมโบ้",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1200,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m10-03.webp"
  },
  {
    "id": "mb-m10-04",
    "name": "ปูอัดแผ่นสำหรับทอดกรอบ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 790,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m10-04.webp"
  },
  {
    "id": "mb-m10-05",
    "name": "ปูอัดทอด A",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m10-05.webp"
  },
  {
    "id": "mb-m10-06",
    "name": "ปูอัดเมก้าแครบสอดไส้ชีส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1420,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m10-06.webp"
  },
  {
    "id": "mb-m11-01",
    "name": "ก้ามโอเชี่ยน",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1370,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m11-01.webp"
  },
  {
    "id": "mb-m11-02",
    "name": "กุ้งแม็กนั่ม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1250,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m11-02.webp"
  },
  {
    "id": "mb-m11-03",
    "name": "กุ้งระเบิด",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1450,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m11-03.webp"
  },
  {
    "id": "mb-m11-04",
    "name": "กุ้งหิมะ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1360,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m11-04.webp"
  },
  {
    "id": "mb-m11-05",
    "name": "ก้ามล็อบสเตอร์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1520,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m11-05.webp"
  },
  {
    "id": "mb-m11-06",
    "name": "ก้ามมหาชัย",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1270,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m11-06.webp"
  },
  {
    "id": "mb-m12-01",
    "name": "ลูกชิ้นหมึก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1690,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m12-01.webp"
  },
  {
    "id": "mb-m12-02",
    "name": "ลูกชิ้นเศรษฐี",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1430,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m12-02.webp"
  },
  {
    "id": "mb-m12-03",
    "name": "ลูกชิ้นปลา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1260,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m12-03.webp"
  },
  {
    "id": "mb-m12-04",
    "name": "ลูกชิ้นปลาไจแอนท์",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1260,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m12-04.webp"
  },
  {
    "id": "mb-m12-05",
    "name": "ลูกชิ้นกุ้ง",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1490,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m12-05.webp"
  },
  {
    "id": "mb-m12-06",
    "name": "ลูกชิ้นกุ้งมังกร",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1540,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m12-06.webp"
  },
  {
    "id": "mb-m13-01",
    "name": "แซนด์วิชเต้าหู้",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1500,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m13-01.webp"
  },
  {
    "id": "mb-m13-02",
    "name": "ทอดมันปลา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1370,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m13-02.webp"
  },
  {
    "id": "mb-m13-03",
    "name": "ปูอัดลายเสือ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 775,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m13-03.webp"
  },
  {
    "id": "mb-m13-04",
    "name": "มินิชาบู",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 990,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m13-04.webp"
  },
  {
    "id": "mb-m13-05",
    "name": "เต๋าเต๋า",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 780,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m13-05.webp"
  },
  {
    "id": "mb-m13-06",
    "name": "คานิมากิ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m13-06.webp"
  },
  {
    "id": "mb-m14-01",
    "name": "ชิกุวะ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1100,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m14-01.webp"
  },
  {
    "id": "mb-m14-02",
    "name": "ดอกไม้ทะเล",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1410,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m14-02.webp"
  },
  {
    "id": "mb-m14-03",
    "name": "เต้าหู้ปลา",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1430,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m14-03.webp"
  },
  {
    "id": "mb-m14-04",
    "name": "เต้าหู้หมึก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1520,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m14-04.webp"
  },
  {
    "id": "mb-m14-05",
    "name": "ปูเบนโตะพลัส",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1155,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m14-05.webp"
  },
  {
    "id": "mb-m14-06",
    "name": "ปูอัดคานิโกะ 12 ซม.",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1100,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m14-06.webp"
  },
  {
    "id": "mb-m15-01",
    "name": "ปูอัดคานิโกะ 7 ซม.",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1100,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m15-01.webp"
  },
  {
    "id": "mb-m15-02",
    "name": "ปูอัดซุปเปอร์แครบ",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1290,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m15-02.webp"
  },
  {
    "id": "mb-m15-03",
    "name": "ปูอัดทอด B",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1290,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m15-03.webp"
  },
  {
    "id": "mb-m15-04",
    "name": "หมึกฮอกไกโด",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1590,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m15-04.webp"
  },
  {
    "id": "mb-m15-05",
    "name": "หมูกำไลไส้เห็ดหอม",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1800,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m15-05.webp"
  },
  {
    "id": "mb-m15-06",
    "name": "กุยช่ายปลาสติ๊ก",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1330,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m15-06.webp"
  },
  {
    "id": "mb-m16-01",
    "name": "ปลาม้วนไส้ไข่เค็ม PFP",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1690,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m16-01.webp"
  },
  {
    "id": "mb-m16-03",
    "name": "เต้าหู้ชีส PFP",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1590,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m16-03.webp"
  },
  {
    "id": "mb-m16-04",
    "name": "ฟองเต้าหู้ซีฟู้ด PFP",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1590,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m16-04.webp"
  },
  {
    "id": "mb-m16-05",
    "name": "ฟองเต้าหู้ชีส PFP",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1660,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m16-05.webp"
  },
  {
    "id": "mb-m16-06",
    "name": "เต้าหู้ปลาแผ่น PFP",
    "category": "ของแช่ฟรีสและของทอด",
    "featured": false,
    "size": "ขั้นต่ำ 1 ลัง/รายการ",
    "price": 1200,
    "unit": "ลัง",
    "status": "in",
    "image": "images/items/mb-m16-06.webp"
  }
];
